# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}

      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Install Dependencies
          command: bundle install

      - save_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bin/gem
            - /usr/local/bin/bundle
            - .bundle

      - run:
          name: Create ~/.netrc
          command: cp spec/fixtures/.netrc ~/

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
